workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      android:
        ndk: 27.0.12077973
    scripts:
      - name: Clean & Get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
