name: zhaiyana
description: A Flutter project for sports field booking and management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  supabase_flutter: ^2.9.1
  intl: ^0.20.2
  uuid: ^4.5.1

  # UI & Features
  table_calendar: ^3.0.9
  share_plus: ^11.0.0
  app_links: ^3.4.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
